---
title: "geom_density -- SDSS 2023 workshop"
output: html_document
date: "2023-05-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

# DENSITY CURVES

## Basic density curve

```{r}
library(ggplot2)
ggplot(faithful) +
  geom_density(aes(x = eruptions))

```


## Two geoms

```{r}
ggplot(faithful, aes(x = eruptions, y = after_stat(density))) +
  geom_histogram(breaks = seq(1.5, 5.5, .25), color = "blue",
                 fill = "cornflowerblue", alpha = .5) +
  geom_density()
```


## Set linewidth and color

```{r}
ggplot(faithful, aes(x = eruptions, y = after_stat(density))) +
  geom_histogram(breaks = seq(1.5, 5.5, .25), color = "blue",
                 fill = "cornflowerblue", alpha = .5) +
  geom_density(linewidth = 1.5, color = "red")
```


## Change the bandwidth

```{r}
ggplot(faithful, aes(x = eruptions, y = after_stat(density))) +
  geom_histogram(breaks = seq(1.5, 5.5, .25), color = "blue",
                 fill = "cornflowerblue", alpha = .5) +
  geom_density(adjust = 0.5, linewidth = 1.5, color = "red")
```


## Add a fill and alpha transparency

```{r}
ggplot(faithful, aes(x = eruptions, y = after_stat(density))) +
  geom_density(adjust = 0.5, linewidth = 1.5, color = "red",
               fill = "red", alpha = 0.25)
```

## Exercises

Create density curves with or without density histograms using variables from the `swiss` or `ggplot2movies` datasets.



